### PR TITLE
Revert "Java 11 on CI (#152)"

### PR DESCRIPTION
**Pull request by hannesa2**
This reverts commit e5141ef3054579e14273ae4b81d6db39951a9c3b.

### CODE REVIEW

**Comment by hannesa2** [comment]
Ahh, they are gone !

**Comment by hannesa2** [comment]
Let revert it and start again ...

**Comment by hannesa2** [comment]
I did several tests and it looks like your repo has the state once-with-matrix-means-always-with-matrix

**Comment by niqdev** [comment]
@hannesa2 thanks for sorting it out 🎉

**Pull request merged**
