### PR TITLE
Better error message

### PR DESCRIPTION
**Pull request by hannesa2**
I wasn't satisfied about a Toast with content **_Error_** That's why I tried to improved it and run into a lot of red code lines and see `Butterknife` ! Sorry, the time of `Butterknife` is over ! 

I converted two Activities into Kotlin and use `ViewBinding`, and at least I improved the Toast message

### CODE REVIEW

**Comment by niqdev** [comment]
That's great!

**Comment by niqdev** [comment]
I haven't published the app in the store in a while. Is there a github action to automate that? Ideally every time there is a new tag it should also update the app in the store.

**Comment by hannesa2** [comment]
You have to run a gradle task https://github.com/Triple-T/gradle-play-publisher and you should de/encrypt the keystore.

Sorry, for Playstore publish I've no public repo, but I do the keystore handling and publish it to github release
https://github.com/hannesa2/mlkit/tree/OneSample/android/signing The other stuff for inspiration is here https://github.com/hannesa2/mlkit/blob/OneSample/.github/workflows/Android-CI-release.yml.

What's _publish it to github release_ ?
It's publish release apk without playstore https://github.com/hannesa2/githubAppUpdate

**Comment by niqdev** [comment]
I've just created a new issue referencing your comment or it will get lost, thanks for the feedback

**Review by niqdev — APPROVED** [review]

**Pull request merged**
