### PR TITLE
more reliably stop MjpegViewDefault thread, log exceptions

### PR DESCRIPTION
**Pull request by alexbell**
Was having problems with cleaning up backing activity/fragments when my video feed disconnected due to network problems.  With these changes the backing fragment is garbage collected as expected after being removed.

These changes may be pretty specific to my situation, but I don't anticipate them causing problems for anybody else.

Thanks for your work on the library! 👍

### CODE REVIEW

**Comment by niqdev** [comment]
Thanks Alex! :+1:

**Comment by niqdev** [comment]
I'll upgrade and release the new version with your changes soon, please if you use this library in a project and would you like to reference it in the Readme you are welcome!

**Comment by niqdev** [comment]
@alexbell I've just released version `1.1.0` with your changes

**Comment by alexbell** [comment]
@niqdev 👍  thanks, i would update the README if the project wasn't under NDA :(

**Pull request merged**
