### PR TITLE
Release job

### PR DESCRIPTION
**Pull request by hannesa2**
You will need under `settings->security` two variables

```
bintray.user
bintray.apikey
```

When you want to publish to bintray as well. This task isn't triggered current automatically

### CODE REVIEW

**Comment by niqdev** [comment]
You might want to wait that I merge all the other PRs before rebase with master

**Comment by niqdev** [comment]
@hannesa2 Once this this merged and I set those 2 secrets in the settings, it's enough to push a tag to release it on Bintray?

**Comment by hannesa2** [comment]
> Once this is merged and I set those 2 secrets in the settings, it's enough to push a tag to release it on Bintray?

Exactly 👍

> Would you mind testing it locally?

I already did it https://github.com/hannesa2/ipcam-view/releases

> Do you suggest Jitpack

Jitpack already works on my fork https://jitpack.io/#hannesa2/ipcam-view

> Bintray

Untested, I've no credential. But I guess the gradle task is missing in release job

> I would like to use only one of the two tbh

It's up to you. But the one doesn't exclude the other one

> If yes would you mind updating the readme to show how to pull

Maybe the link is enough ? Or a batch ? 
image

**Comment by hannesa2** [comment]
I don't understand why this job doesn't start 

image

**Comment by hannesa2** [comment]
Can it be, that you changed in the settings something too much, because no job is starting anymore ?

**Comment by niqdev** [comment]
> Can it be, that you changed in the settings something too much, because no job is starting anymore ?

Honestly, I'm not sure, cos it worked for the other prs - if it's stuck you can try to open another pr maybe :thinking: 

> Untested, I've no credential. But I guess the gradle task is missing in release job

I can add the credentials, but I'm not sure what tasks are needed from the github action

> I think the JitPack badge (replace Bintray) + repository import in the readme it's enough to start - unless you know how to fix the release on Bintray too.

**Comment by niqdev** [comment]
Screenshot from 2021-03-28 19-06-01

Well... I think we've already an answer...

**Comment by hannesa2** [comment]
I will create same PR on different branch name. Maybe it will help ?

**Pull request closed without merging**
