### PR TITLE
Support x86_64

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by niqdev** [comment]
> But the best way would be not to check in this *.so files and let jitpack.io/github build it every time
@hannesa2 any chance you can fix this? otherwise I'll merge it like that if your are confident with it

**Comment by hannesa2** [comment]
I can do it in an other pull request, but I promise nothing

**Comment by hannesa2** [comment]
Hold on and wait for #161

**Comment by niqdev** [comment]
I'll close this one in favour of #161 - Thank you!

**Pull request closed without merging**
