### PR TITLE
Release with auto generated changelog

### PR DESCRIPTION
**Pull request by hannesa2**
You can control grouping by github labels. 
Please see an example here https://github.com/gitx/gitx/releases/tag/0.21

### CODE REVIEW

**Comment by hannesa2** [comment]
I can't set labels. I've no permission to do it here

**Comment by niqdev** [comment]
@hannesa2 That's great, I've added the new labels https://github.com/niqdev/ipcam-view/labels, is that ok?

**Comment by hannesa2** [comment]
This labeling is optional. If you don't label, they are nominated as "other changes".
But only you can label it, all others are missing this permission.
Currently there are two possible groups https://github.com/niqdev/ipcam-view/pull/221/files#diff-409fea45635f464aa0592700a92cf483be2f5b21b60f8f1b383756067ee79213R8-R13

- breaking-change
- enhancement
- and of course: label nothing is a  "other changes".

**Comment by niqdev** [comment]
Cool, thanks for the changes!

**Comment by hannesa2** [comment]
Just some words to the changelog. All PR where not labeled, that's why all changes are "Other changes" https://github.com/niqdev/ipcam-view/releases/tag/2.4.0

**Pull request merged**
