### PR TITLE
Fix scaling issue

### PR DESCRIPTION
**Pull request by zaptoopa**
Hi @niqdev I just tested the new version 2.3.1. Unfortunately, I found that I implemented something wrong in the last PR; the scaling didn't work properly. Here I have a fix that I have tested extensively. Sorry for the hassel.

### CODE REVIEW

**Comment by niqdev** [comment]
no worries, and thanks for taking the time to review it!

**Comment by niqdev** [comment]
the release of `2.3.2` is failing, there is a mem [issue](https://github.com/niqdev/ipcam-view/runs/4443192149?check_suite_focus=true) apparently
```
 * What went wrong:
Metaspace
```
@zaptoopa could you please pull the latest version and checkout what configurations are you using locally? we might need to override them - I don't have the sdk installed or the project running locally atm. Thank you!

**Comment by hannesa2** [comment]
> the release of `2.3.2` is failing, there is a mem [issue](https://github.com/niqdev/ipcam-view/runs/4443192149?check_suite_focus=true) apparently
> 
> ```
>  * What went wrong:
> Metaspace
> ```

I would simply push the re-run action button. 
image

I can't because of missing rights

**Comment by niqdev** [comment]
i did that 3 times already

**Comment by hannesa2** [comment]
> This might have been caused by the latest gradle upgrade btw

I don't think so, this pull request was successful. But hold on, pull requests are just do `./gradlew assembleDebug` with separated `./gradlew check` and release do `./gradlew clean build` at once.

I would recomment to do on release only
`./gradlew assembleRelease`
instead off
`./gradlew clean build`  
btw this `clean` is obsolete

**Comment by hannesa2** [comment]
an other solution could be 
image

**Comment by zaptoopa** [comment]
> could you please pull the latest version and checkout what configurations are you using locally? 

Gradle Plugin Version = 7.0.3
Gradle Version = 7.3.1
JAVA = 11.0.10

The only thing I set is the JAVA version (v11); the other values are my basic settings. The build run without issues on AVD with API 29 and 30.

I see only warnings and that `PreferenceManager` in `IpCamDefaultActivity.kt` and `IpCamSnapshotActivity.kt` is deprecated. It could be solved using `implementation 'androidx.preference:preference-ktx:1.1.1'`

**Comment by zaptoopa** [comment]
ohh, ok, after cleaning and rebuilding i see the warnings

clean_n_rebuild

**Comment by hannesa2** [comment]
@zaptoopa  you should run `./gradlew :app:lintAnalyzeDebug`

**Comment by hannesa2** [comment]
Local the error prone task
image

**Comment by zaptoopa** [comment]
I have some warnings like `memcpy` that i can trace back to the commit #161 , but in the end the build is:

BUILD SUCCESSFUL in 17s
53 actionable tasks: 53 executed

Should i paste the output here?

**Comment by hannesa2** [comment]
A complete `./gradlew clean build` like in CI job works local

image

For me this is the evidence to have a problem on CI machines only

**Comment by hannesa2** [comment]
I guess this is the solution on CI https://github.com/niqdev/ipcam-view/pull/178

Only this is needed 8ad9fbec87922

**Comment by hannesa2** [comment]
The other commit 0e24f788105 only slows down CI

**Comment by zaptoopa** [comment]
> For me this is the evidence to have a problem on CI machines only

yes, i agree, especially since it is built locally

**Comment by niqdev** [comment]
Thanks for the quick feedback! yes i think it's just a problem on the CI machine

**Comment by zaptoopa** [comment]
thx @hannesa2, @niqdev nice, it seems to be ok now. will the release be bumped to version 2.3.2?

**Pull request merged**
