### PR TITLE
Add scale fit display mode

### PR DESCRIPTION
**Pull request by zaptoopa**
PR added to issue #163 to scale inputStream in landscape mode; especially for 4:3 cameras

### CODE REVIEW

**Comment by niqdev** [comment]
@zaptoopa that's great! Can you please review the conflicts? Thanks!

**Comment by zaptoopa** [comment]
Hi @niqdev , I would resolve the conflicts but unfortunately I can't see the relevant parts! The only thing that I see is that two files are affected.

**Comment by zaptoopa** [comment]
FYI: the "Merge github action" commit includes some earlier commits like "More Kotlin (#170)".

**Comment by hannesa2** [comment]
It looks fine on my side 
image

**Comment by hannesa2** [comment]
I rebased this pull request and made a new one (I can't push to _zaptoopa:feature/displaymode-scale_) and I see 3 ! green builds 
image


compared to 2 yellow ones here

image

Maybe @zaptoopa should rebase too ?

**Comment by niqdev** [comment]
@zaptoopa thanks for your contribution! I think it got messed up with @hannesa2 refactor, so I'll merge #176 in favour of this. I'll release shortly a new version

**Comment by niqdev** [comment]
version `2.3.1` should be available shortly

**Comment by zaptoopa** [comment]
Sounds great

**Pull request closed without merging**
