### PR TITLE
add flipHorizontal and flipVertical

### PR DESCRIPTION
**Pull request by xeno14**
* Add flip vertical and horizontal

```java
    void flipHorizontal(boolean flip);
    void flipVertical(boolean flip);
```

* `flipSource` is mapped to flip horizontal for backward comaptibility

### Example

```java
    private void loadIpCam() {
        Mjpeg.newInstance()
            .credential(getPreference(PREF_AUTH_USERNAME), getPreference(PREF_AUTH_PASSWORD))
            .open(getPreference(PREF_IPCAM_URL), TIMEOUT)
            .subscribe(
                inputStream -> {
                    mjpegView.setSource(inputStream);
                    mjpegView.setDisplayMode(calculateDisplayMode());
                    mjpegView.flipHorizontal(true);  // is equivalent to flipSource(true)
                    mjpegView.flipVertical(true);    // able to flip vertical as well
                    mjpegView.showFps(true);
                },
                throwable -> {
                    Log.e(getClass().getSimpleName(), "mjpeg error", throwable);
                    Toast.makeText(this, "Error", Toast.LENGTH_LONG).show();
                });
    }
```

### CODE REVIEW

**Comment by niqdev** [comment]
Awesome, sorry for the late response, but I was on holiday.
Before merge the PR and release a new version, could you please update the readme and, if you can, also add an activity in the demo app to show the functionality?
Thanks a lot!

**Comment by xeno14** [comment]
@niqdev Thank you for your comment. I have added preferences into the demo app. Updated README as well.

screenshot_20180826-193147

## Original image

Copied from https://jpeg.org/jpeg/

screenshot_20180826-193222

## Flip horizontal
screenshot_20180826-193235

## Flip vertical
screenshot_20180826-193251

## Flip horizontal and vertical
screenshot_20180826-193311

**Comment by niqdev** [comment]
@xeno14 thanks!
I'm gonna merge your PR and release a new version of the lib and the app

**Comment by xeno14** [comment]
@niqdev Thank you for merging my PR. Note that screenshot-settings.png needs to be updated.

**Comment by niqdev** [comment]
* released library version `1.4.0` with your changes
* released app version `1.8.0` with updated camera urls
* updated screenshots
:smiley:

**Pull request merged**
