### PR TITLE
CI and fix build

### LINKED ISSUE #97: Build is broken
#84 brokes the build

image

### PR DESCRIPTION
**Pull request by hannesa2**
closes #97

### CODE REVIEW

**Comment by hannesa2** [comment]
I recommend to merge this first, then all dependabot pull request will be build as well

**Comment by niqdev** [comment]
@hannesa2 I'm not familiar with actions, how do I monitor if the build fails, where do I see the logs? I Usually use Travis/CircleCI

**Comment by hannesa2** [comment]
It's more advanced as Travis, it can keep artifacts as well. eg lint reports https://github.com/niqdev/ipcam-view/pull/99/files#diff-ad74395badb28f27b88fb4b57e85d1842121d2f05191a3c60f287b3dae983a60R54-R57

Here you have developer sample https://github.com/hannesa2/ipcam-view/runs/2212347174

**Comment by hannesa2** [comment]
Now you can do this https://github.com/niqdev/ipcam-view/pull/103#issuecomment-808917521

**Comment by hannesa2** [comment]
... and it builds now 
image

**Comment by niqdev** [comment]
Brilliant! Just to know, do you have any interest in helping to maintain the project?
I haven't developed with Android in a while, so it's kinda hard to keep it up to date. Help is always more than welcome!

**Comment by hannesa2** [comment]
Most projects will die because of a single maintainer 👎

To avoid this, i can do maintain a little bit too.
But it will be not my main repo

**Comment by niqdev** [comment]
I have interests in keeping it alive, cos I use this in another [project](https://github.com/openwebnet/openwebnet-android), which as well I have a hard time maintaining. But what you have done is already a lot :bowing_man: I appreciate the help!

**Pull request merged**
