### PR TITLE
Add OnFrameCaptured Event

### PR DESCRIPTION
**Pull request by Selameab**
Capability of calling a function when a new frame is received...

### CODE REVIEW

**Comment by niqdev** [comment]
Great!
Before merge the PR could you please (maybe you need to do a new one and cancel this)
* revert the commit on `IpCamDefaultActivity.java` I think are just empty spaces
* add an example in `IpCamDefaultActivity.java` with a button or in the actionbar to show how to take a screenshot (it would be fantastic) and maybe store the file - it must be very simple, is just a demo app 
* if you have an app on GitHub or on Play, can you share it in the [README](https://github.com/niqdev/ipcam-view#apps-that-use-this-library)?

Thanks

**Comment by Selameab** [comment]
I've made the changes!
Unfortunately, I haven't published anything that uses mjpeg yet.

**Comment by niqdev** [comment]
Great! I'll publish a new version of the library and update the app on the store.
Thanks

**Comment by niqdev** [comment]
I've upgraded the library to the stable version `1.0.0` with your feature and changed the sample activity. The updated library is now in beta testing and I will release it after.
I've also reopened another issue to record videos, the solution seem similar to yours.

**Pull request merged**
